install.packages("xlsx")
install.packages("foreign")
install.packages("foreach")
install.packages("multicore")
install.packages("XML")
install.packages("googleVis")
install.packages("reshape")
install.packages("Design")
install.packages("MASS")
install.packages ("stats")
install.packages ("gbm")
install.packages ("RWeka")
install.packages ("mda")
install.packages("rpart")
install.packages("caTools")
install.packages("caret")
install.packages("swirl")
install.packages("shiny")
install.packages("UsingR")
library("caret")
data(segmentationData)
load("~/My R/phsample.RData")